title: Notchlab - initiate, improve & iterate
description: > # this means to ignore newlines until "baseurl:"
  Notchlab  - where ideas grow, revolution starts
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "https://t-notch.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: notch_lab #if your site has a twitter account, enter it here

# Author Settings
author: T-Notch # add your name
author-img: t-notch.png # add your photo
about-author: "Idea planted by one, grows with thousands and becomes reality with millions" # add description
location: "Belgium - Sol III"
social-twitter: notch_lab # add your Twitter handle
social-github: t-notch # add your Github handle
#social-medium: @t.notch # add your medium handle
social-email: t.notch@zoho.eu # add your Email address
# Disqus
# discus-identifier: t-notch # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

#pagination:
  #enabled: true
  #per_page: 8
  #permalink: '/page/:num/'
  #title: ':title | :num of :max'
  #limit: 0
  #sort_field: 'date'
  #sort_reverse: true
 ## extension: htm
 ## indexpage: 'default'
  #trail: 
    #before: 2
    #after: 2

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

